IF EXISTS(SELECT * FROM sysobjects WHERE TYPE='p' AND NAME='MURSPPLANTILLATIPOPLAZA')
DROP PROCEDURE MURSPPLANTILLATIPOPLAZA
GO
CREATE PROC MURSPPLANTILLATIPOPLAZA          
AS BEGIN          
          
          
          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA          
          
          
CREATE TABLE TABLAPERSONALTIPOPLAZA ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA1') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA1          
CREATE TABLE TABLAPERSONALTIPOPLAZA1 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA2') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA2          
CREATE TABLE TABLAPERSONALTIPOPLAZA2 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA3') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA3          
CREATE TABLE TABLAPERSONALTIPOPLAZA3 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA4') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA4          
CREATE TABLE TABLAPERSONALTIPOPLAZA4 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA5') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA5          
CREATE TABLE TABLAPERSONALTIPOPLAZA5 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA6') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA6          
CREATE TABLE TABLAPERSONALTIPOPLAZA6 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA7') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA7          
CREATE TABLE TABLAPERSONALTIPOPLAZA7 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),              NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA8') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA8          
CREATE TABLE TABLAPERSONALTIPOPLAZA8 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA9') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA9          
CREATE TABLE TABLAPERSONALTIPOPLAZA9 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA10') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA10          
CREATE TABLE TABLAPERSONALTIPOPLAZA10 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA10') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA10          
CREATE TABLE TABLAPERSONALTIPOPLAZA10 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA11') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA11          
CREATE TABLE TABLAPERSONALTIPOPLAZA11 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA12') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA12          
CREATE TABLE TABLAPERSONALTIPOPLAZA12 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT, 
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA13') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA13          
CREATE TABLE TABLAPERSONALTIPOPLAZA13 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA14') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA14          
CREATE TABLE TABLAPERSONALTIPOPLAZA14 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA15') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA15          
CREATE TABLE TABLAPERSONALTIPOPLAZA15 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA16') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA16          
CREATE TABLE TABLAPERSONALTIPOPLAZA16 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA17') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA17          
CREATE TABLE TABLAPERSONALTIPOPLAZA17 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA18') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA18          
CREATE TABLE TABLAPERSONALTIPOPLAZA18 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA19') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA19          
CREATE TABLE TABLAPERSONALTIPOPLAZA19 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA20') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA20          
CREATE TABLE TABLAPERSONALTIPOPLAZA20 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA21') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA21          
CREATE TABLE TABLAPERSONALTIPOPLAZA21 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,         
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA22') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA22          
CREATE TABLE TABLAPERSONALTIPOPLAZA22 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA23') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA23          
CREATE TABLE TABLAPERSONALTIPOPLAZA23 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA24') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA24          
CREATE TABLE TABLAPERSONALTIPOPLAZA24 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA25') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA25          
CREATE TABLE TABLAPERSONALTIPOPLAZA25 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
          
          
          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA26') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA26          
CREATE TABLE TABLAPERSONALTIPOPLAZA26 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA27') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA27          
CREATE TABLE TABLAPERSONALTIPOPLAZA27 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA28') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA28          
CREATE TABLE TABLAPERSONALTIPOPLAZA28 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA29') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA29          
CREATE TABLE TABLAPERSONALTIPOPLAZA29 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))     
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA30') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA30          
CREATE TABLE TABLAPERSONALTIPOPLAZA30 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))  
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA31') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA31          
CREATE TABLE TABLAPERSONALTIPOPLAZA31 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))     
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLAPERSONALTIPOPLAZA32') AND TYPE='U') DROP TABLE TABLAPERSONALTIPOPLAZA32          
CREATE TABLE TABLAPERSONALTIPOPLAZA32 ( ID INT IDENTITY (1,1),          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))         
----***********************          
---************************          
INSERT INTO  TABLAPERSONALTIPOPLAZA (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,          
SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   --LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
             
WHERE P.ESTATUS='ALTA'          
AND  P.TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='DIRECTOR GENERAl'          
          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
          
INSERT INTO  TABLAPERSONALTIPOPLAZA1 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,          
SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   --LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
             
WHERE P.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='coordinador'          
          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
          
INSERT INTO  TABLAPERSONALTIPOPLAZA2 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,          
SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   --LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
             
WHERE P.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='jefe de division'          
          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
          
INSERT INTO  TABLAPERSONALTIPOPLAZA3 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,          
SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
             
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='jefe de unidad'          
          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
---*******      
INSERT INTO  TABLAPERSONALTIPOPLAZA31 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR C "E"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
 ---*******      
INSERT INTO  TABLAPERSONALTIPOPLAZA32 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR C "A"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************             
          
---*******          
INSERT INTO  TABLAPERSONALTIPOPLAZA4 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=ISNULL(dbo.fnPlazasEnUso(p.Plaza,p.Personal),0)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR TITULAR "C"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
---*******          
INSERT INTO  TABLAPERSONALTIPOPLAZA5 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR TITULAR "B"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
---*******          
INSERT INTO  TABLAPERSONALTIPOPLAZA6 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR TITULAR "A"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
          
---*******          
INSERT INTO  TABLAPERSONALTIPOPLAZA7 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INGENIERO TITULAR "A"'    --      
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
---*******          
INSERT INTO  TABLAPERSONALTIPOPLAZA8 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR ASOCIADO "C"'    --      
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO---*******          
---**************          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA9 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='TECNOLOGO ASOCIADO "C"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA10 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR ASOCIADO "B"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO      
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA11 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INGENIERO ASOCIADO "B"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO         
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA12 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR ASOCIADO "A"'    --      
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA13 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INGENIERO ASOCIADO "A"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
          
-----******          
-----INGENIERO ASOCIADO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA14 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR ASISTENTE "C"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA15 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR ASISTENTE "B"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA16 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO       
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='INVESTIGADOR ASISTENTE "A"'    ---aqui--      
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA17 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='TECNICO TITULAR DE CARRERA "A"'    --      
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA18 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='TECNICO AUXILIAR "C"'    --      
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA19 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='TECNICO AUXILIAR "B"'    --      
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA20 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='TECNICO AUXILIAR "A"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA21 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='TECNICO ASOCIADO "A"'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA22 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='SECRETARIA DE COORDINADOR'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA23 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='CHOFER DE COORDINADOR'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA24 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='CHOFER DE COORDINADOR GENERAL'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA25 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='SECRETARIA JEFE DE UNIDAD'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA26 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='JEFE OFICINA ADMINISTRATIVA'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA27 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='COORDINADOR ADMINISTRATIVO'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA28 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='SECRETARIA DE DIRECTOR'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA29 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='ANALISTA DE PROYECTOS'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
--***************          
INSERT INTO  TABLAPERSONALTIPOPLAZA30 (COORDINACION,NOMBRE,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO,grupocategoriaimt )          
SELECT 'COORDINACION'=ISNULL(U.NOMBRE,''),          
'NOMBRE'=APELLIDOPATERNO+' '+APELLIDOMATERNO+' '+P.NOMBRE ,SDI,          
'CATEGORIA'=ISNULL(DESCRIPCION,''),'PUESTOPERSONAL'=ISNULL(P.NIVELPUESTOIMT,''),ISNULL(P.DEPARTAMENTO,'')          
,'PLAZAS'=(SELECT COUNT(Plaza.Plaza) FROM Plaza WHERE plaza.Plaza=p.Plaza)
,'ENUSO'=dbo.fnPlazasEnUso(p.Plaza,p.Personal)
,ISNULL(grupocategoriaimt,'')          
FROM PERSONAL P  LEFT OUTER JOIN UEN U  ON  P.UEN=U.UEN          
   LEFT OUTER JOIN PUESTO O ON  P.PUESTO=O.PUESTO          
   LEFT OUTER JOIN IMTPLAZA H ON  P.Puesto=H.Puesto AND P.PUESTO=H.PUESTO          
WHERE p.ESTATUS='ALTA'          
AND  TIPOCONTRATO='CONFIANZA'          
AND DESCRIPCION ='ANALISTA PROGRAMADOR'          
ORDER BY P.NIVELPUESTOIMT,CATEGORIA ,grupocategoriaimt desc,APELLIDOPATERNO          
          
          
---****************          
--- TABLA FINAL          
          
IF EXISTS (SELECT * FROM SYSOBJECTS WHERE ID=OBJECT_ID('DBO.TABLATIPOPLAZA') AND TYPE='U') DROP TABLE TABLATIPOPLAZA          
          
          
CREATE TABLE TABLATIPOPLAZA ( id int,          
           COORDINACION VARCHAR(70),          
      NOMBRE  VARCHAR(70),          
     SDI  MONEY,          
     CATEGORIA VARCHAR(70),          
     PUESTOPERSONAL VARCHAR(70),          
     DEPARTAMENTO VARCHAR(70),          
     PLAZAS  INT,          
     ENUSO  INT,          
     grupocategoriaimt VARCHAR(70))          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
          
SELECT * FROM TABLAPERSONALTIPOPLAZA          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA1          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA2 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA3 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )  
SELECT * FROM TABLAPERSONALTIPOPLAZA31 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA32 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA4 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA5 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA6 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA7 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA8 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )      
SELECT * FROM TABLAPERSONALTIPOPLAZA9 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA10 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA11 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA12 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA13 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA14 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA15 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA16 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA17 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA18 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA19 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA20 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA21 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA22 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA23 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA24 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA25 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA26 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA27 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA28 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA29 order by categoria          
insert into TABLATIPOPLAZA (id,COORDINACION,NOMBRE ,SDI,CATEGORIA,PUESTOPERSONAL,DEPARTAMENTO,PLAZAS,ENUSO ,grupocategoriaimt )          
SELECT * FROM TABLAPERSONALTIPOPLAZA30 order by categoria           
          
          
          
          
select * from TABLATIPOPLAZA          
          
          
          
END          
          
          
/*          
          
EXEC MURSPPLANTILLATIPOPLAZA          
          
*/ 